export const HOST = 'http://localhost:8080';
export const USER_TOKEN = 'USER_TOKEN';
export const USER_TOKEN_IS_EMPTY = 'USER_TOKEN_IS_EMPTY';

export const REGISTER_URI = '/register';
export const LOGIN_URI = '/login';

// Register
export const ATTEMPT_REGISTER_FAILED = 'ATTEMPT_REGISTER_FAILED';
export const ATTEMPT_REGISTER_SUCCESSFULLY = 'ATTEMPT_REGISTER_SUCCESSFULLY';

// Login
export const ATTEMPT_LOGIN_FAILED = 'ATTEMPT_LOGIN_FAILED';
export const ATTEMPT_LOGIN_SUCCESSFULLY = 'ATTEMPT_LOGIN_SUCCESSFULLY';

export const ATTEMPT_LOGOUT = 'ATTEMPT_LOGOUT';
